### ISSUE TITLE
Unpack outputs empty queries unless -multi-line is set

### ISSUE THREAD

**Issue by bgirardeau-figma** [chainguard-dev/osqtool#4]
By default, running `osqtool unpack pack.conf` created a directory of SQL files with blank queries (only the metadata comments for description, interval, etc) instead of the expected queries in the pack. 

This is easy to workaround by passing in the `-multi-line` flag, which gives the intended behavior.

I think the issue is that `SingleLineQuery` is not set by `LoadPack` before this code runs: https://github.com/chainguard-dev/osqtool/blob/dd065eaf546ae8418683d955a4ad69f4a18d05a3/cmd/osqtool/main.go#L192

**Comment by tstromberg** [comment]
Thanks for the report! I was able to reproduce this and will fix this bug shortly.
